### ISSUE TITLE
New release, please?

### ISSUE THREAD

**Issue by WesWedding** [JohannesKlauss/react-fps#474]
I am currently working on a project that is using the latest React, React 17, and npm doesn't want to install react-fps because the peerDependency is React 16 on the last release, about a year ago.

I can, of course, use  `npm install JohannesKlauss/react-fps#master` but I think it'd be great if we could get a new tag pushed.

Thank you!

**Comment by JohannesKlauss** [comment]
@WesWedding Thank you for raising this issue. Actually the whole `peerDependencies` section was set up wrongly. This is fixed now in version `1.0.5`
