### ISSUE TITLE
Wrong average after tab switching

### ISSUE THREAD

**Issue by arelaxend** [JohannesKlauss/react-fps#72]
Hi there,

**What is the bug** 

The average is wrong when you switch tab for a period of time.

For example, 
- set a windowWidth of 3
- switch tab with 30s elapse time
- you see that the current fps is short (e.g. 10)
- the next avg value should be 10+10+60/3=40 but it display 10.x

**What is the expected result ?**
A correct value for the average.

A.

**Comment by JohannesKlauss** [comment]
Thank you for the bug report, gonna check that out.

**Comment by JohannesKlauss** [comment]
@arelaxend This bug is fixed with version 1.0.4
